export const REQUEST_PERSON_LIST = 'REQUEST_PERSON_LIST'
export const FETCH_PERSON_LIST = 'FETCH_PERSON_LIST'
export const RECEIVE_PERSON_LIST = 'RECEIVE_PERSON_LIST'

export const CREATE_NEW_PERSON = 'CREATE_NEW_PERSON'
export const AWAIT_NEW_PERSON = 'AWAIT_NEW_PERSON'
export const RECEIVE_NEW_PERSON = 'RECEIVE_NEW_PERSON'

export const GOTO_BACK = 'GOTO_BACK'
export const GOTO_CREATE = 'GOTO_CREATE'
export const GOTO_MAIN = 'GOTO_MAIN'
export const GOTO_SHOW = 'GOTO_SHOW'

export const CREATE_FORM_SUBMIT = 'CREATE_FORM_SUBMIT'
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAILURE = 'CREATE_FORM_FAILURE'

export const NOTIFICATION = 'PUSH_NOTIFICATION'
export const NOTIFICATION_CLEAR = 'PUSH_NOTIFICATION_CLEAR'